import imgApi from '~/public/images/imgAPI';

const testimonialsData = [
  {
    avatar: imgApi.avatar[0],
    name: 'farvision7f',
    title: 'fiverr.com',
    text: 'Very professional and helpful',
    x: 100,
    y: 150,
  },
  {
    name: 'etomcuisine',
    title: 'fiverr.com',
    text: 'I would recommend to anyone looking to create or update their social media account. Thank you for the work!',
    x: 120,
    y: 100,
  },
  {
    name: 'marketingmaps',
    title: 'fiverr.com',
    text: 'Very quick and great communication. Will use again. Highly recommend',
    x: 400,
    y: 40,
  },
  {
    avatar: imgApi.avatar[3],
    name: 'moredaysoff',
    title: 'fiverr.com',
    text: 'Great communication and work was delivered early, would recommend.',
    x: 500,
    y: 300,
  },
  {
    avatar: imgApi.avatar[4],
    name: 'onetwenty1',
    title: 'fiverr.com',
    text: 'Worked well together. It was great and delivered on time! Thanks again! Would work with him again and again and I recommend others to do the same!',
    x: 270,
    y: 220,
  },
  {
    name: 'malakiamatias',
    title: 'fiverr.com',
    text: 'Am happy with the work, very knowledgeable.',
    x: 100,
    y: 200,
  },
  {
    avatar: imgApi.avatar[6],
    name: 'usjungle',
    title: 'fiverr.com',
    text: 'Great to work with. Sumon delivered faster than expected, was a very good communicator and everything was smooth. Im very satisfied, his work is very good for the money. Thanks for all',
    x: 100,
    y: 40,
  },
  {
    name: 'cyrilgupta1',
    title: 'fiverr.com',
    text: 'Done on time Thanks',
    x: 330,
    y: 100,
  },
  {
    avatar: imgApi.avatar[1],
    name: 'hitthegrid',
    title: 'fiverr.com',
    text: 'Great Job, we surly would recommend',
    x: 30,
    y: 50,
  },
  {
    avatar: imgApi.avatar[9],
    name: 'hitthegrid',
    title: 'fiverr.com',
    text: 'The Seller was outstanding, prompt and efficient! Excellent work, highly recommend...',
    x: 400,
    y: 150,
  },
  {
    name: 'serenitycashflo',
    title: 'fiverr.com',
    text: 'AWESOME AND SO PROFESSIONAL. He answered all my questions and delivered just like he said. I am very happy with his work and I will continue to do business with him and recommend him.',
    x: 480,
    y: 100,
  },
  {
    name: 'hustlemama',
    title: 'fiverr.com',
    text: 'Absolutely exceptional service and delivered as promised. Will definitely be using again!',
    x: 250,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: 'maridee8',
    title: 'fiverr.com',
    text: 'The seller took on the project like it was his own. He showed genuine interest in wanting to improve and fix all the issues I had. I look forward to a long term relationship with this seller. We already have agreed on phase two of my project.',
    x: 150,
    y: 300,
  },
  {
    avatar: imgApi.avatar[7],
    name: 'marshallamps',
    title: 'fiverr.com',
    text: 'Enjoyed working with Sumon and I have found a new friend. Very trustworthy and would not hesitate in recommending his gig. Thank you Sumon we will work together again.',
    x: 300,
    y: 140,
  },
  {
    name: 'vrajavadhus',
    title: 'fiverr.com',
    text: 'The best help I’ve gotten for YouTube channel growth. He brought the seo up and even helped with my channel optimization as a bonus! Very committed and helpful. Will continue to use for future jobs! Would highly recommend. Exceeded my expectations',
    x: 480,
    y: 280,
  }
];

export default testimonialsData;
